engines:
  rubocop:
    enabled: true
    #checks:
    #  Rubocop/Metrics/ClassLength:
    #    enabled: false
  brakeman:
    enabled: true
  eslint:
    enabled: true
  csslint:
    enabled: true
  duplication:
    enabled: true
    config:
      languages:
      - ruby:
      - javascript:
ratings:
  paths:
  - app/**
  - lib/**
  - "**.rb"
  - "**.go"
exclude_paths:
  - .overcommit.yml
  - "app/assets/javascripts/cable.js"
  - "app/channels/**/*"
  - spec/**/*
  - "**/vendor/**/*"
