before_script:
  - cp config/database.yml.travis config/database.yml
  - psql -c 'create database travis_ci_test;' -U postgres
language: ruby
rvm:
  - 2.2
script: COV=1 rspec
services:
  - redis-server
  - postgresql
