addons:
  postgresql: 9.6
before_script:
  - cp config/database.yml.travis config/database.yml
  - psql -c 'create database travis_ci_test;' -U postgres
dist: trusty
env:
  - COV=1
language: ruby
rvm:
  - 2.4.1
script:
  - bundle exec rails db:migrate RAILS_ENV=test
  - bundle exec rspec
services:
  - redis-server
